In [ ]:
import pandas as pd
from sklearn.metrics import r2_score,accuracy_score,mean_squared_error
import statsmodels.api as sm
import seaborn as sns
sns.set()

In [ ]:
df = pd.read_csv("1.03.+Dummies.csv")
df

SAT   GPA Attendance
0   1714  2.40         No
1   1664  2.52         No
2   1760  2.54         No
3   1685  2.74         No
4   1693  2.83         No
..   ...   ...        ...
79  1936  3.71        Yes
80  1810  3.71        Yes
81  1987  3.73         No
82  1962  3.76        Yes
83  2050  3.81        Yes

[84 rows x 3 columns]

In [ ]:
df['Attendance'] = df['Attendance'].map({'Yes':1,"No":0})

In [ ]:
df

SAT   GPA  Attendance
0   1714  2.40           0
1   1664  2.52           0
2   1760  2.54           0
3   1685  2.74           0
4   1693  2.83           0
..   ...   ...         ...
79  1936  3.71           1
80  1810  3.71           1
81  1987  3.73           0
82  1962  3.76           1
83  2050  3.81           1

[84 rows x 3 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
model  = LinearRegression()
model.fit(df[['SAT','GPA']],df['Attendance'])

LinearRegression()

In [ ]:

# Predicted values
ypredi = model.predict(df[['SAT', 'GPA']])

# R2 score
r2 = r2_score(df['Attendance'], ypredi)
print(f"R2 Score: {r2}")

# Mean Squared Error
mse = mean_squared_error(df['Attendance'], ypredi)
print(f"Mean Squared Error: {mse}")


R2 Score: 0.310358686369835
Mean Squared Error: 0.17153068387484968


In [ ]:
y = df['Attendance']
x = sm.add_constant(df[['SAT', 'GPA']])
results = sm.OLS(y,x).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             Attendance   R-squared:                       0.310
Model:                            OLS   Adj. R-squared:                  0.293
Method:                 Least Squares   F-statistic:                     18.23
Date:                Sun, 12 Jan 2025   Prob (F-statistic):           2.91e-07
Time:                        05:48:47   Log-Likelihood:                -45.145
No. Observations:                  84   AIC:                             96.29
Df Residuals:                      81   BIC:                             103.6
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.9881      0.821     -2.422      0.018      -3.621      -0.355
SAT           -0.0008      0.001     -1.473      0.144      -0.002       0.000
GPA            1.2056      0.221      5.451      0.000       0.766       1.646
==============================================================================
Omnibus:                       58.031   Durbin-Watson:                   1.717
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                6.597
Skew:                          -0.062   Prob(JB):                       0.0369
Kurtosis:                       1.633   Cond. No.                     3.30e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.3e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
df = pd.read_csv("1.01.+Simple+linear+regression (1).csv")
df

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [ ]:
x = df['SAT']
y = df['GPA']


In [ ]:
xm = x.values.reshape(-1,1)
xm

array([[1714],
       [1664],
       [1760],
       [1685],
       [1693],
       [1670],
       [1764],
       [1764],
       [1792],
       [1850],
       [1735],
       [1775],
       [1735],
       [1712],
       [1773],
       [1872],
       [1755],
       [1674],
       [1842],
       [1786],
       [1761],
       [1722],
       [1663],
       [1687],
       [1974],
       [1826],
       [1787],
       [1821],
       [2020],
       [1794],
       [1769],
       [1934],
       [1775],
       [1855],
       [1880],
       [1849],
       [1808],
       [1954],
       [1777],
       [1831],
       [1865],
       [1850],
       [1966],
       [1702],
       [1990],
       [1925],
       [1824],
       [1956],
       [1857],
       [1979],
       [1802],
       [1855],
       [1907],
       [1634],
       [1879],
       [1887],
       [1730],
       [1953],
       [1781],
       [1891],
       [1964],
       [1808],
       [1893],
       [2041],
       [1893],
       [1832],
       [18

In [ ]:
xm.shape

(84, 1)

In [ ]:
model.fit(xm,y)

LinearRegression()

In [ ]:
model.coef_

array([0.00165569])

In [ ]:
model.predict([[2000]])

array([3.5864164])

In [ ]:
new_data = pd.DataFrame(data=[2020,1987],columns=['SAT'])
new_data

SAT
0  2020
1  1987

In [ ]:
model.predict(new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([3.61953016, 3.56489246])

In [ ]:
model.score(xm,y)

0.40600391479679754

display coef and and interncept

In [4]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv("real_estate_price_size_year.csv")
df

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

In [10]:
x = df[['size','year']]
y = df['price']

In [11]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [12]:
model.intercept_

-5772267.017463279

In [14]:
model.coef_

array([ 227.70085401, 2916.78532684])

In [15]:
model.predict([[1000,2010]])

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([318172.34348865])

In [16]:
model.score(x,y)

0.7764803683276795

In [19]:
def adj_r(x,y):
  n = x.shape[0]
  p = x.shape[1]
  r2 = model.score(x,y)
  adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
  return adjusted_r2

In [20]:
adj_r(x,y)

0.7718717161282502

# **we need to find the f_regression to see that whether we have to drop thecolumns or not**

In [21]:
from sklearn.feature_selection import f_regression

In [23]:
p_values = f_regression(x,y)[1]

In [24]:
p_values.round(3)

array([0.   , 0.357])